name-template: 'v$NEXT_PATCH_VERSION'
tag-template: '$NEXT_PATCH_VERSION'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
branches:
  - 'master'
categories:
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'dependencies'

template: |
  ## Changes

  $CHANGES

  ## Compare

  https://github.com/heavenshell/py-sqlalchemy_seed/compare/$PREVIOUS_TAG...$NEXT_PATCH_VERSION
